import type { Card } from "./types";

/**
 * Seed catalogue of popular Malaysian credit cards.
 *
 * IMPORTANT: Reward rates, caps, fees and income requirements here are
 * REPRESENTATIVE and were modelled from publicly advertised structures. Banks
 * change card policies frequently — every card carries `lastVerified` and
 * `sourceUrl` so staleness is visible. Confirm figures with the issuing bank
 * before treating any recommendation as financial advice.
 *
 * Conversion assumptions (for normalising points/miles to RM):
 *  - Points cards: ~RM0.01 per point unless noted (typical cashback-redemption value).
 *  - Miles cards: ~RM0.04–0.05 per mile (typical economy-redemption value).
 */
export const CARDS: Card[] = [
  // ---------------------------------------------------------------- Cashback
  {
    id: "maybank-2-gold",
    name: "Maybank 2 Cards Gold (Amex)",
    bank: "Maybank",
    network: "Amex",
    rewardType: "cashback",
    color: "#f59e0b",
    annualFee: 0,
    feeWaiver: { type: "always" },
    minAnnualIncome: 30000,
    baseRule: { category: "general", rate: 0.0025, unit: "percent" },
    earnRules: [
      {
        category: "general",
        rate: 0.05,
        unit: "percent",
        monthlyCap: 50,
        notes: "5% weekend cashback on Amex, capped RM50/month",
      },
    ],
    perks: ["No annual fee for life", "Weekend cashback"],
    lastVerified: "2026-01-15",
    sourceUrl: "https://www.maybank2u.com.my/maybank2u/malaysia/en/personal/cards/credit/maybank_2_gold.page",
  },
  {
    id: "cimb-cashback",
    name: "CIMB Cash Rebate Platinum",
    bank: "CIMB",
    network: "Mastercard",
    rewardType: "cashback",
    color: "#dc2626",
    annualFee: 0,
    feeWaiver: { type: "always" },
    minAnnualIncome: 30000,
    baseRule: { category: "general", rate: 0.002, unit: "percent" },
    earnRules: [
      {
        category: "petrol",
        rate: 0.08,
        unit: "percent",
        monthlyCap: 30,
        minMonthlySpend: 0,
        notes: "8% on petrol, capped RM30/month",
      },
      {
        category: "dining",
        rate: 0.02,
        unit: "percent",
        monthlyCap: 30,
        notes: "2% dining, shared RM30/month cap with groceries",
      },
      {
        category: "groceries",
        rate: 0.02,
        unit: "percent",
        monthlyCap: 30,
        notes: "2% groceries",
      },
    ],
    perks: ["No annual fee", "Strong petrol rebate"],
    lastVerified: "2026-01-20",
    sourceUrl: "https://www.cimb.com.my/en/personal/banking-with-us/cards/credit-cards.html",
  },
  {
    id: "hlb-wse-cashback",
    name: "Hong Leong WISE Card",
    bank: "Hong Leong",
    network: "Mastercard",
    rewardType: "cashback",
    color: "#1d4ed8",
    annualFee: 0,
    feeWaiver: { type: "always" },
    minAnnualIncome: 24000,
    baseRule: { category: "general", rate: 0.003, unit: "percent" },
    earnRules: [
      {
        category: "dining",
        rate: 0.08,
        unit: "percent",
        monthlyCap: 30,
        minMonthlySpend: 1000,
        notes: "Up to 8% on dining/groceries/petrol with min RM1,000 spend",
      },
      {
        category: "groceries",
        rate: 0.08,
        unit: "percent",
        monthlyCap: 30,
        minMonthlySpend: 1000,
      },
      {
        category: "petrol",
        rate: 0.08,
        unit: "percent",
        monthlyCap: 30,
        minMonthlySpend: 1000,
      },
    ],
    perks: ["No annual fee", "Choose your bonus category"],
    lastVerified: "2026-01-10",
    sourceUrl: "https://www.hlb.com.my/en/personal-banking/credit-cards.html",
  },
  {
    id: "bank-rakyat-cashback",
    name: "Bank Rakyat Platinum-i",
    bank: "Bank Rakyat",
    network: "Mastercard",
    rewardType: "cashback",
    color: "#16a34a",
    annualFee: 0,
    feeWaiver: { type: "always" },
    minAnnualIncome: 24000,
    baseRule: { category: "general", rate: 0.002, unit: "percent" },
    earnRules: [
      {
        category: "groceries",
        rate: 0.05,
        unit: "percent",
        monthlyCap: 25,
        notes: "5% groceries, capped RM25/month",
      },
      {
        category: "bills",
        rate: 0.05,
        unit: "percent",
        monthlyCap: 25,
        notes: "5% on selected bills",
      },
    ],
    perks: ["Shariah-compliant", "No annual fee"],
    lastVerified: "2026-01-05",
    sourceUrl: "https://www.bankrakyat.com.my/cards",
  },
  {
    id: "uob-one",
    name: "UOB One Card",
    bank: "UOB",
    network: "Visa",
    rewardType: "cashback",
    color: "#0e7490",
    annualFee: 195,
    feeWaiver: { type: "spend", threshold: 12000 },
    minAnnualIncome: 30000,
    baseRule: { category: "general", rate: 0.003, unit: "percent" },
    earnRules: [
      {
        category: "general",
        rate: 0.05,
        unit: "percent",
        monthlyCap: 50,
        minMonthlySpend: 1500,
        notes: "Up to 5% quarterly rebate with consistent min spend",
      },
      {
        category: "petrol",
        rate: 0.05,
        unit: "percent",
        monthlyCap: 50,
        minMonthlySpend: 1500,
      },
      {
        category: "groceries",
        rate: 0.05,
        unit: "percent",
        monthlyCap: 50,
        minMonthlySpend: 1500,
      },
    ],
    perks: ["High flat cashback for steady spenders"],
    lastVerified: "2026-01-18",
    sourceUrl: "https://www.uob.com.my/personal/cards/credit-cards.page",
  },
  {
    id: "alliance-visa-cashback",
    name: "Alliance Bank Visa Cashback",
    bank: "Alliance",
    network: "Visa",
    rewardType: "cashback",
    color: "#9333ea",
    annualFee: 0,
    feeWaiver: { type: "always" },
    minAnnualIncome: 24000,
    baseRule: { category: "general", rate: 0.002, unit: "percent" },
    earnRules: [
      {
        category: "online",
        rate: 0.05,
        unit: "percent",
        monthlyCap: 30,
        notes: "5% online spend, capped RM30/month",
      },
      {
        category: "groceriesOnline",
        rate: 0.05,
        unit: "percent",
        monthlyCap: 30,
      },
      {
        category: "ewallet",
        rate: 0.05,
        unit: "percent",
        monthlyCap: 30,
      },
    ],
    perks: ["Strong online & e-wallet rebate", "No annual fee"],
    lastVerified: "2026-01-12",
    sourceUrl: "https://www.alliancebank.com.my/personal/cards.aspx",
  },
  {
    id: "publicbank-quantum",
    name: "Public Bank Quantum",
    bank: "Public Bank",
    network: "Visa",
    rewardType: "cashback",
    color: "#b91c1c",
    annualFee: 0,
    feeWaiver: { type: "always" },
    minAnnualIncome: 24000,
    baseRule: { category: "general", rate: 0.001, unit: "percent" },
    earnRules: [
      {
        category: "online",
        rate: 0.05,
        unit: "percent",
        monthlyCap: 30,
        notes: "5% on online, dining & contactless (shared cap)",
      },
      {
        category: "dining",
        rate: 0.05,
        unit: "percent",
        monthlyCap: 30,
      },
      {
        category: "contactless",
        rate: 0.05,
        unit: "percent",
        monthlyCap: 30,
      },
    ],
    perks: ["No annual fee", "Popular all-rounder rebate card"],
    lastVerified: "2026-01-22",
    sourceUrl: "https://www.pbebank.com/Personal-Banking/Cards/Credit-Cards.aspx",
  },
  {
    id: "rhb-smart-cashback",
    name: "RHB Smart Value Visa",
    bank: "RHB",
    network: "Visa",
    rewardType: "cashback",
    color: "#1e40af",
    annualFee: 0,
    feeWaiver: { type: "always" },
    minAnnualIncome: 24000,
    baseRule: { category: "general", rate: 0.002, unit: "percent" },
    earnRules: [
      {
        category: "bills",
        rate: 0.1,
        unit: "percent",
        monthlyCap: 25,
        notes: "10% rebate on selected utility bills, capped RM25/month",
      },
      {
        category: "groceries",
        rate: 0.02,
        unit: "percent",
        monthlyCap: 20,
      },
    ],
    perks: ["High utility-bill rebate", "No annual fee"],
    lastVerified: "2026-01-08",
    sourceUrl: "https://www.rhbgroup.com/cards/index.html",
  },

  // ------------------------------------------------------------------ Points
  {
    id: "maybank-2-platinum",
    name: "Maybank 2 Cards Platinum (Visa)",
    bank: "Maybank",
    network: "Visa",
    rewardType: "points",
    color: "#7c3aed",
    annualFee: 0,
    feeWaiver: { type: "always" },
    minAnnualIncome: 60000,
    pointValueRM: 0.012,
    baseRule: { category: "general", rate: 1, unit: "pointsPerRM" },
    earnRules: [
      {
        category: "general",
        rate: 5,
        unit: "pointsPerRM",
        notes: "5x TreatsPoints on weekends",
      },
    ],
    perks: ["No annual fee for life", "TreatsPoints rewards catalogue"],
    lastVerified: "2026-01-15",
    sourceUrl: "https://www.maybank2u.com.my/maybank2u/malaysia/en/personal/cards/credit/maybank_2_platinum.page",
  },
  {
    id: "cimb-visa-signature",
    name: "CIMB Visa Signature",
    bank: "CIMB",
    network: "Visa",
    rewardType: "points",
    color: "#be123c",
    annualFee: 0,
    feeWaiver: { type: "always" },
    minAnnualIncome: 60000,
    pointValueRM: 0.01,
    baseRule: { category: "general", rate: 1, unit: "pointsPerRM" },
    earnRules: [
      {
        category: "online",
        rate: 10,
        unit: "pointsPerRM",
        monthlyCap: 3000,
        notes: "10x points on online, travel & groceries (cap 3,000 bonus pts/mo)",
      },
      {
        category: "travel",
        rate: 10,
        unit: "pointsPerRM",
        monthlyCap: 3000,
      },
      {
        category: "groceries",
        rate: 10,
        unit: "pointsPerRM",
        monthlyCap: 3000,
      },
    ],
    perks: ["10x bonus points categories", "No annual fee"],
    lastVerified: "2026-01-20",
    sourceUrl: "https://www.cimb.com.my/en/personal/banking-with-us/cards/credit-cards.html",
  },
  {
    id: "hlb-emirates-points",
    name: "Hong Leong Emirates Platinum",
    bank: "Hong Leong",
    network: "Mastercard",
    rewardType: "points",
    color: "#0f766e",
    annualFee: 0,
    feeWaiver: { type: "always" },
    minAnnualIncome: 60000,
    pointValueRM: 0.011,
    baseRule: { category: "general", rate: 1, unit: "pointsPerRM" },
    earnRules: [
      {
        category: "travel",
        rate: 3,
        unit: "pointsPerRM",
        notes: "3x points on overseas & travel spend",
      },
      {
        category: "dining",
        rate: 2,
        unit: "pointsPerRM",
      },
    ],
    perks: ["No annual fee", "Travel-tilted points"],
    lastVerified: "2026-01-10",
    sourceUrl: "https://www.hlb.com.my/en/personal-banking/credit-cards.html",
  },
  {
    id: "ambank-visa-signature",
    name: "AmBank Visa Signature",
    bank: "AmBank",
    network: "Visa",
    rewardType: "points",
    color: "#ea580c",
    annualFee: 0,
    feeWaiver: { type: "always" },
    minAnnualIncome: 60000,
    pointValueRM: 0.01,
    baseRule: { category: "general", rate: 1, unit: "pointsPerRM" },
    earnRules: [
      {
        category: "groceries",
        rate: 5,
        unit: "pointsPerRM",
        notes: "5x BonusPoints on groceries & petrol",
      },
      {
        category: "petrol",
        rate: 5,
        unit: "pointsPerRM",
      },
    ],
    perks: ["No annual fee", "Groceries & petrol points"],
    lastVerified: "2026-01-14",
    sourceUrl: "https://www.ambank.com.my/eng/cards/credit-cards",
  },
  {
    id: "uob-ppv",
    name: "UOB PRVI Miles (points mode)",
    bank: "UOB",
    network: "Visa",
    rewardType: "points",
    color: "#155e75",
    annualFee: 255,
    feeWaiver: { type: "spend", threshold: 30000 },
    minAnnualIncome: 80000,
    pointValueRM: 0.012,
    baseRule: { category: "general", rate: 1.4, unit: "pointsPerRM" },
    earnRules: [
      {
        category: "travel",
        rate: 3,
        unit: "pointsPerRM",
        notes: "Accelerated points on travel & overseas",
      },
    ],
    perks: ["High base earn rate", "Airport lounge access"],
    lastVerified: "2026-01-18",
    sourceUrl: "https://www.uob.com.my/personal/cards/credit-cards.page",
  },

  // ------------------------------------------------------------------- Miles
  {
    id: "maybank-premier-miles",
    name: "Maybank Premier Visa (Miles)",
    bank: "Maybank",
    network: "Visa",
    rewardType: "miles",
    color: "#0891b2",
    annualFee: 800,
    feeWaiver: { type: "none" },
    minAnnualIncome: 120000,
    mileValueRM: 0.045,
    baseRule: { category: "general", rate: 1, unit: "milesPerRM" },
    earnRules: [
      {
        category: "travel",
        rate: 2,
        unit: "milesPerRM",
        notes: "2 miles per RM on overseas & airline spend",
      },
    ],
    perks: ["Airport lounge access", "Travel insurance", "Premier privileges"],
    lastVerified: "2026-01-15",
    sourceUrl: "https://www.maybank2u.com.my/maybank2u/malaysia/en/personal/cards/credit/premier_visa.page",
  },
  {
    id: "standard-chartered-journey",
    name: "Standard Chartered Journey",
    bank: "Standard Chartered",
    network: "Mastercard",
    rewardType: "miles",
    color: "#047857",
    annualFee: 600,
    feeWaiver: { type: "spend", threshold: 60000 },
    minAnnualIncome: 100000,
    mileValueRM: 0.05,
    baseRule: { category: "general", rate: 1.2, unit: "milesPerRM" },
    earnRules: [
      {
        category: "travel",
        rate: 3,
        unit: "milesPerRM",
        notes: "3 miles per RM on travel & overseas spend",
      },
      {
        category: "online",
        rate: 1.5,
        unit: "milesPerRM",
      },
    ],
    perks: ["Flexible miles transfer", "Lounge access"],
    lastVerified: "2026-01-19",
    sourceUrl: "https://www.sc.com/my/credit-cards/",
  },
  {
    id: "hsbc-travelone",
    name: "HSBC TravelOne",
    bank: "HSBC",
    network: "Visa",
    rewardType: "miles",
    color: "#b91c1c",
    annualFee: 0,
    feeWaiver: { type: "always" },
    minAnnualIncome: 100000,
    mileValueRM: 0.045,
    baseRule: { category: "general", rate: 1, unit: "milesPerRM" },
    earnRules: [
      {
        category: "travel",
        rate: 2.5,
        unit: "milesPerRM",
        notes: "Accelerated miles on travel & overseas",
      },
      {
        category: "dining",
        rate: 1.5,
        unit: "milesPerRM",
      },
    ],
    perks: ["No annual fee", "Multiple airline/hotel transfer partners"],
    lastVerified: "2026-01-21",
    sourceUrl: "https://www.hsbc.com.my/credit-cards/",
  },
  {
    id: "ambank-enrich",
    name: "AmBank Enrich Visa Infinite",
    bank: "AmBank",
    network: "Visa",
    rewardType: "miles",
    color: "#c2410c",
    annualFee: 488,
    feeWaiver: { type: "spend", threshold: 48000 },
    minAnnualIncome: 100000,
    mileValueRM: 0.045,
    baseRule: { category: "general", rate: 1.25, unit: "milesPerRM" },
    earnRules: [
      {
        category: "travel",
        rate: 2,
        unit: "milesPerRM",
        notes: "Direct Enrich Points earning on travel",
      },
    ],
    perks: ["Malaysia Airlines Enrich miles", "Lounge access"],
    lastVerified: "2026-01-16",
    sourceUrl: "https://www.ambank.com.my/eng/cards/credit-cards",
  },
];

export const CARD_BY_ID: Record<string, Card> = CARDS.reduce(
  (acc, c) => {
    acc[c.id] = c;
    return acc;
  },
  {} as Record<string, Card>,
);
